name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # Build, test, and analyze in one job to keep reports/classes available
  qa:
    name: Test and SonarCloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # OPTIONAL: Create/ensure project exists and default branch maps to GitHub "main"
      - name: Setup SonarCloud project
        id: setupSonar
        uses: nelsoncanarinho/setup-sonar@v1.0.0
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Unit Tests
        run: mvn -B test

      # If JaCoCo is configured in pom, verify will produce coverage before sonar
      - name: SonarCloud Scan (Maven)
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.organization=${{ steps.setupSonar.outputs.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ steps.setupSonar.outputs.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build artifact
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
